# Generated by Django 3.0.14 on 2021-05-12 09:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: \'09XXXXXXXXX\'. "09" than 9 digit digits allowed.', regex='^09\\d{9}$')])),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryToCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryToCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('version', models.CharField(max_length=300)),
                ('sn', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FirewallChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_description', models.TextField(blank=True)),
                ('new_Firewall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Firewall')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: \'09XXXXXXXXX\'. "09" than 9 digit digits allowed.', regex='^09\\d{9}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedFromCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiber_port_num', models.CharField(max_length=300)),
                ('eth_port_num', models.CharField(max_length=300)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('Firewall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Firewall')),
                ('Firewall_changes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.FirewallChange')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Company')),
                ('company_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.CompanyPerson')),
                ('device_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.DeviceProblem')),
                ('received_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Staff')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Status')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedFromCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiber_port_num', models.CharField(max_length=300)),
                ('eth_port_num', models.CharField(max_length=300)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('Firewall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Firewall')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category')),
                ('device_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.DeviceProblem')),
                ('received_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Staff')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_to_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.DeliveryToCategory')),
                ('delivery_to_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.DeliveryToCompany')),
                ('received_from_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ReceivedFromCategory')),
                ('received_from_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.ReceivedFromCompany')),
            ],
        ),
        migrations.AddField(
            model_name='deliverytocompany',
            name='Firewall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Firewall'),
        ),
        migrations.AddField(
            model_name='deliverytocompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Company'),
        ),
        migrations.AddField(
            model_name='deliverytocompany',
            name='company_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.CompanyPerson'),
        ),
        migrations.AddField(
            model_name='deliverytocompany',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Staff'),
        ),
        migrations.AddField(
            model_name='deliverytocompany',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Status'),
        ),
        migrations.AddField(
            model_name='deliverytocategory',
            name='Firewall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Firewall'),
        ),
        migrations.AddField(
            model_name='deliverytocategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category'),
        ),
        migrations.AddField(
            model_name='deliverytocategory',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Staff'),
        ),
        migrations.AddField(
            model_name='deliverytocategory',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Status'),
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Firewall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Firewall')),
            ],
        ),
    ]
