# Generated by Django 3.1.2 on 2021-03-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryperson',
            name='delivery_person',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_bog',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recievedperson',
            name='recieved_person',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
