# Generated by Django 3.0.14 on 2021-05-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='available',
            old_name='Firewall',
            new_name='firewall',
        ),
        migrations.RenameField(
            model_name='deliverytocategory',
            old_name='Firewall',
            new_name='firewall',
        ),
        migrations.RenameField(
            model_name='deliverytocompany',
            old_name='Firewall',
            new_name='firewall',
        ),
        migrations.RenameField(
            model_name='receivedfromcategory',
            old_name='Firewall',
            new_name='firewall',
        ),
        migrations.RenameField(
            model_name='receivedfromcompany',
            old_name='Firewall',
            new_name='firewall',
        ),
        migrations.RenameField(
            model_name='receivedfromcompany',
            old_name='Firewall_changes',
            new_name='firewall_changes',
        ),
    ]
