# Generated by Django 3.0.14 on 2021-05-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210512_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firewallchange',
            old_name='new_Firewall',
            new_name='new_firewall',
        ),
    ]
