# Generated by Django 3.0.1 on 2021-04-17 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210410_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='phone_number',
            field=models.CharField(default='09000000000', max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: \'09XXXXXXXXX\'. "09" than 9 digit digits allowed.', regex='^09\\d{9}$')]),
            preserve_default=False,
        ),
    ]
