# Generated by Django 3.0.1 on 2021-04-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_deliveryperson_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFromCompany',
            fields=[
                ('delivery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Delivery')),
            ],
            bases=('app.delivery',),
        ),
        migrations.CreateModel(
            name='DeliveryFromVendor',
            fields=[
                ('delivery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Delivery')),
            ],
            bases=('app.delivery',),
        ),
        migrations.CreateModel(
            name='ReceivedFromCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_from_category', models.CharField(max_length=300)),
                ('fibr_port_num', models.CharField(max_length=300)),
                ('eth_port_num', models.CharField(max_length=300)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('send_to_company_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('device_bog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Device')),
                ('devilery_person_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DeliveryPerson')),
                ('fireWall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FireWall')),
                ('received_person_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.RecievedPerson')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivedFromVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_from_category', models.CharField(max_length=300)),
                ('fibr_port_num', models.CharField(max_length=300)),
                ('eth_port_num', models.CharField(max_length=300)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('send_to_company_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('device_bog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Device')),
                ('devilery_person_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DeliveryPerson')),
                ('fireWall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FireWall')),
                ('received_person_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.RecievedPerson')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_to_category_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Received',
        ),
    ]
