# Generated by Django 3.0.14 on 2021-05-12 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210512_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
