# Generated by Django 3.0.1 on 2021-04-18 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210418_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedFromCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fibr_port_num', models.CharField(max_length=300)),
                ('eth_port_num', models.CharField(max_length=300)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('send_to_company_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category')),
                ('device_bog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Device')),
                ('devilery_person_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DeliveryPerson')),
                ('fireWall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FireWall')),
                ('received_person_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.RecievedPerson')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_to_category',
        ),
        migrations.RemoveField(
            model_name='receivedfromcompany',
            name='received_from_category',
        ),
        migrations.RenameModel(
            old_name='DeliveryFromVendor',
            new_name='DeliveryFromCategory',
        ),
        migrations.DeleteModel(
            name='ReceivedFromVendor',
        ),
        migrations.AddField(
            model_name='delivery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
        migrations.AddField(
            model_name='receivedfromcompany',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Category'),
        ),
    ]
