# Generated by Django 3.0.14 on 2021-05-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_operation_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivedfromcategory',
            name='eth_port_num',
        ),
        migrations.RemoveField(
            model_name='receivedfromcategory',
            name='fiber_port_num',
        ),
        migrations.RemoveField(
            model_name='receivedfromcompany',
            name='eth_port_num',
        ),
        migrations.RemoveField(
            model_name='receivedfromcompany',
            name='fiber_port_num',
        ),
        migrations.AddField(
            model_name='firewall',
            name='eth_port_num',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firewall',
            name='fiber_port_num',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
