# Generated by Django 3.0.1 on 2021-04-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210418_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='name_phone',
        ),
        migrations.AddField(
            model_name='delivery',
            name='devilery_person_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DeliveryPerson'),
        ),
    ]
