# Generated by Django 3.1.2 on 2021-03-06 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_bog', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FireWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('version', models.CharField(max_length=300)),
                ('sn', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RecievedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_person', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_from_category', models.CharField(max_length=300)),
                ('fibr_port_num', models.CharField(default='SOME STRING', max_length=300)),
                ('eth_port_num', models.CharField(default='SOME STRING', max_length=300)),
                ('device_bog', models.CharField(default='SOME STRING', max_length=300)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('send_to_company_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(default='SOME STRING', max_length=300)),
                ('delivery_row', models.CharField(default='SOME STRING', max_length=300)),
                ('description', models.CharField(default='SOME STRING', max_length=1000)),
                ('devilery_person_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.deliveryperson')),
                ('fireWall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.firewall')),
                ('received_person_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.recievedperson')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_to_category_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_to_category', models.CharField(max_length=300)),
                ('description', models.CharField(default='SOME STRING', max_length=1000)),
                ('fireWall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.firewall')),
                ('name_phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.deliveryperson')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.status')),
            ],
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300)),
                ('replace', models.CharField(max_length=300)),
                ('fireWall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.firewall')),
            ],
        ),
    ]
